apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalScalerServer.subdomain }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: {{ .Values.externalScalerServer.service.grpc.protocolName }}
    port: {{ .Values.externalScalerServer.service.grpc.port }}
    targetPort: {{ .Values.externalScalerServer.service.grpc.targetPort }}
    protocol: TCP
  selector:
    name: {{ .Values.externalScalerServer.name }}
---
apiVersion: apps/v1
kind: {{ .Values.nginx.kind }}
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: {{ .Values.nginx.name }}
  podManagementPolicy: {{ .Values.nginx.podManagementPolicy }}
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.nginx.name }}
    spec:
      hostname: {{ .Values.nginx.name }}
      subdomain: {{ .Values.nginx.subdomain }}
      containers:
        - name: {{ .Values.nginx.name }}
          image: {{ $.Values.nginx.image }}:{{ $.Values.nginx.tag }}
          imagePullPolicy: {{ $.Values.nginx.pullPolicy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.externalScalerServer.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.externalScalerServer.name }}
  template:
    metadata:
      name: {{ .Values.externalScalerServer.name }}
      labels:
        name: {{ .Values.externalScalerServer.name }}
    spec:
      hostname: {{ .Values.externalScalerServer.name }}
      subdomain: {{ .Values.externalScalerServer.subdomain }}
      containers:
        - name: {{ .Values.externalScalerServer.name }}
          image: {{ $.Values.externalScalerServer.image }}:{{ $.Values.externalScalerServer.tag }}
          imagePullPolicy: {{ $.Values.externalScalerServer.pullPolicy }}
---
